repos:
  # --- Ruff for linting + fixing ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3   # ( latest known stable tag)
    hooks:
      - id: ruff
        name: Run Ruff (lint + autofix)
        args: [--fix]  # automatically fix issues where possible
      - id: ruff-format
        name: Run Ruff Formatter
  # --- Run pytest before commit ---
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: bash -c "PYTHONPATH=src python -m pytest -q"
        language: system
        types: [python]
        pass_filenames: false