repos:
  # --- Ruff for linting + fixing ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3   # ( latest known stable tag)
    hooks:
      - id: ruff
        name: Run Ruff (lint + autofix)
        args: [--fix]  # automatically fix issues where possible
      - id: ruff-format
        name: Run Ruff Formatter
