repos:
# --- Black autoformatter ---
  - repo: https://github.com/psf/black
    rev: 24.10.0   # Use the latest stable version
    hooks:
      - id: black
        name: Format Python code with Black
        language_version: python3

  # --- Pylint linter ---
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5   # use latest pylint mirror version
    hooks:
      - id: pylint
        name: Run Pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--disable=C0114,C0115,C0116"]  # optional: disable docstring warnings
